### ISSUE TITLE
Incremental Replication

### ISSUE THREAD

**Issue by mzjgithub** [airbnb/reair#33]
1. Can you give an  " Incremental Replication"  example ？
2. Have you used the  " Incremental Replication"  in the production environment?

**Comment by plypaul** [comment]
@mzjgithub - Yes, incremental replication has been deployed in production at Airbnb and has been in use for ~1.5 years. One big change was the move to replicate changes using the Thrift metastore audit log instead of the Hive client audit log. 

For more details, please checkout the `Incremental Replication` at https://medium.com/airbnb-engineering/reair-easy-to-use-tools-for-migrating-and-replicating-petabyte-scale-data-warehouses-5153f8a433da#.7b8lcvlzmh.
